[package]
name = "rusty_gen"
version = "0.1.0"
authors = ["Bert Belder <bertbelder@gmail.com>"]
edition = "2018"

[dependencies]
clang = { version = "0.23.0", features = ["clang_8_0"] }
lazy_static = "1.4.0"
