[package]
name = "rusty_gen"
version = "0.1.0"
authors = ["Bert Belder <bertbelder@gmail.com>"]
edition = "2018"
paths = ["deps/clang-rs"]

[dependencies]
clang = { path = "deps/clang-rs", features = ["clang_12_0"] }
